.TH TESTBOBGUI 1
.SH NAME
testbobgui \- test if the Bobgui library is working
.SH SYNOPSIS
.B testbobgui
.SH "DESCRIPTION"
testbobgui is a sample program using the Bobgui library. It tests all the
widgets and buttons and other fun things that Bobgui lets you do,
and is a good example program to see how to make Bobgui work.
.SH BUGS
Absolutely none whatsoever.
.SH AUTHOR
Peter Mattis <petm@xcf.berkeley.edu>, 
Spencer Kimball <spencer@xcf.berkeley.edu>,
and Josh MacDonald <jmacd@xcf.berkeley.edu>
