/* BOBGUI - A modern native application and UI framework
 * Copyright (C) 1995-1997 Peter Mattis, Spencer Kimball and Josh MacDonald
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * Maintained and evolved by the Bobgui contributors.  See the AUTHORS
 * file for contributor credits and repository history for implementation
 * details and ongoing refactor work.
 */

#pragma once

#define __BOBGUI_H_INSIDE__

#include <bobgui/css/bobguicss.h>
#include <bobgui/svg/bobguisvg.h>
#include <gdk/gdk.h>
#include <gsk/gsk.h>

#include <bobgui/bobguiaboutdialog.h>
#include <bobgui/bobguiaccelgroup.h>
#include <bobgui/bobguiaccessible.h>
#include <bobgui/bobguiaccessiblehypertext.h>
#include <bobgui/bobguiaccessiblerange.h>
#include <bobgui/bobguiaccessibletext.h>
#include <bobgui/bobguiactionable.h>
#include <bobgui/bobguiactionbar.h>
#include <bobgui/bobguiadjustment.h>
#include <bobgui/bobguialertdialog.h>
#include <bobgui/deprecated/bobguiappchooser.h>
#include <bobgui/deprecated/bobguiappchooserdialog.h>
#include <bobgui/deprecated/bobguiappchooserwidget.h>
#include <bobgui/deprecated/bobguiappchooserbutton.h>
#include <bobgui/bobguiapplication.h>
#include <bobgui/bobguiapplicationwindow.h>
#include <bobgui/bobguiaspectframe.h>
#include <bobgui/deprecated/bobguiassistant.h>
#include <bobgui/bobguiatcontext.h>
#include <bobgui/bobguibinlayout.h>
#include <bobgui/bobguibitset.h>
#include <bobgui/bobguibookmarklist.h>
#include <bobgui/bobguiboolfilter.h>
#include <bobgui/bobguiborder.h>
#include <bobgui/bobguiboxlayout.h>
#include <bobgui/bobguibox.h>
#include <bobgui/bobguibuildable.h>
#include <bobgui/bobguibuilder.h>
#include <bobgui/bobguibuilderlistitemfactory.h>
#include <bobgui/bobguibuilderscope.h>
#include <bobgui/bobguibutton.h>
#include <bobgui/bobguicalendar.h>
#include <bobgui/deprecated/bobguicellarea.h>
#include <bobgui/deprecated/bobguicellareabox.h>
#include <bobgui/deprecated/bobguicellareacontext.h>
#include <bobgui/deprecated/bobguicelleditable.h>
#include <bobgui/deprecated/bobguicelllayout.h>
#include <bobgui/deprecated/bobguicellrenderer.h>
#include <bobgui/deprecated/bobguicellrendereraccel.h>
#include <bobgui/deprecated/bobguicellrenderercombo.h>
#include <bobgui/deprecated/bobguicellrendererpixbuf.h>
#include <bobgui/deprecated/bobguicellrendererprogress.h>
#include <bobgui/deprecated/bobguicellrendererspin.h>
#include <bobgui/deprecated/bobguicellrendererspinner.h>
#include <bobgui/deprecated/bobguicellrenderertext.h>
#include <bobgui/deprecated/bobguicellrenderertoggle.h>
#include <bobgui/deprecated/bobguicellview.h>
#include <bobgui/bobguicenterbox.h>
#include <bobgui/bobguicenterlayout.h>
#include <bobgui/bobguicheckbutton.h>
#include <bobgui/deprecated/bobguicolorbutton.h>
#include <bobgui/deprecated/bobguicolorchooser.h>
#include <bobgui/deprecated/bobguicolorchooserdialog.h>
#include <bobgui/deprecated/bobguicolorchooserwidget.h>
#include <bobgui/bobguicolordialog.h>
#include <bobgui/bobguicolordialogbutton.h>
#include <bobgui/bobguicolorutils.h>
#include <bobgui/bobguicolumnview.h>
#include <bobgui/bobguicolumnviewcell.h>
#include <bobgui/bobguicolumnviewcolumn.h>
#include <bobgui/bobguicolumnviewrow.h>
#include <bobgui/bobguicolumnviewsorter.h>
#include <bobgui/deprecated/bobguicombobox.h>
#include <bobgui/deprecated/bobguicomboboxtext.h>
#include <bobgui/bobguiconfig.h>
#include <bobgui/bobguiconstraintlayout.h>
#include <bobgui/bobguiconstraint.h>
#include <bobgui/bobguicssprovider.h>
#include <bobgui/bobguicustomlayout.h>
#include <bobgui/bobguicustomsorter.h>
#include <bobgui/bobguidebug.h>
#include <bobgui/deprecated/bobguidialog.h>
#include <bobgui/bobguidialogerror.h>
#include <bobgui/bobguidirectorylist.h>
#include <bobgui/bobguidragicon.h>
#include <bobgui/bobguidragsource.h>
#include <bobgui/bobguidrawingarea.h>
#include <bobgui/bobguidropcontrollermotion.h>
#include <bobgui/bobguidroptarget.h>
#include <bobgui/bobguidroptargetasync.h>
#include <bobgui/bobguidropdown.h>
#include <bobgui/bobguieditable.h>
#include <bobgui/bobguieditablelabel.h>
#include <bobgui/bobguiemojichooser.h>
#include <bobgui/bobguientry.h>
#include <bobgui/bobguientrybuffer.h>
#include <bobgui/deprecated/bobguientrycompletion.h>
#include <bobgui/bobguienumlist.h>
#include <bobgui/bobguienums.h>
#include <bobgui/bobguieventcontroller.h>
#include <bobgui/bobguieventcontrollerfocus.h>
#include <bobgui/bobguieventcontrollerkey.h>
#include <bobgui/bobguieventcontrollerlegacy.h>
#include <bobgui/bobguieventcontrollermotion.h>
#include <bobgui/bobguieventcontrollerscroll.h>
#include <bobgui/bobguiexpander.h>
#include <bobgui/bobguiexpression.h>
#include <bobgui/bobguifixed.h>
#include <bobgui/bobguifixedlayout.h>
#include <bobgui/deprecated/bobguifilechooser.h>
#include <bobgui/deprecated/bobguifilechooserdialog.h>
#include <bobgui/deprecated/bobguifilechoosernative.h>
#include <bobgui/deprecated/bobguifilechooserwidget.h>
#include <bobgui/bobguifiledialog.h>
#include <bobgui/bobguifilefilter.h>
#include <bobgui/bobguifilelauncher.h>
#include <bobgui/bobguifilter.h>
#include <bobgui/bobguifilterlistmodel.h>
#include <bobgui/bobguicustomfilter.h>
#include <bobgui/bobguiflattenlistmodel.h>
#include <bobgui/bobguiflowbox.h>
#include <bobgui/deprecated/bobguifontbutton.h>
#include <bobgui/deprecated/bobguifontchooser.h>
#include <bobgui/deprecated/bobguifontchooserdialog.h>
#include <bobgui/deprecated/bobguifontchooserwidget.h>
#include <bobgui/bobguifontdialog.h>
#include <bobgui/bobguifontdialogbutton.h>
#include <bobgui/bobguiframe.h>
#include <bobgui/bobguigesture.h>
#include <bobgui/bobguigestureclick.h>
#include <bobgui/bobguigesturedrag.h>
#include <bobgui/bobguigesturelongpress.h>
#include <bobgui/bobguigesturepan.h>
#include <bobgui/bobguigesturerotate.h>
#include <bobgui/bobguigesturesingle.h>
#include <bobgui/bobguigesturestylus.h>
#include <bobgui/bobguigestureswipe.h>
#include <bobgui/bobguigesturezoom.h>
#include <bobgui/bobguiglarea.h>
#include <bobgui/bobguigraphicsoffload.h>
#include <bobgui/bobguigrid.h>
#include <bobgui/bobguigridlayout.h>
#include <bobgui/bobguigridview.h>
#include <bobgui/bobguiheaderbar.h>
#include <bobgui/bobguiicontheme.h>
#include <bobgui/bobguiiconpaintable.h>
#include <bobgui/deprecated/bobguiiconview.h>
#include <bobgui/bobguiimage.h>
#include <bobgui/bobguiimcontext.h>
#include <bobgui/bobguiimcontextsimple.h>
#include <bobgui/bobguiimmulticontext.h>
#include <bobgui/deprecated/bobguiinfobar.h>
#include <bobgui/bobguiinscription.h>
#include <bobgui/bobguilabel.h>
#include <bobgui/bobguilayoutmanager.h>
#include <bobgui/bobguilayoutchild.h>
#include <bobgui/bobguilevelbar.h>
#include <bobgui/bobguilistbase.h>
#include <bobgui/bobguilinkbutton.h>
#include <bobgui/bobguilistbox.h>
#include <bobgui/bobguilistheader.h>
#include <bobgui/bobguilistitem.h>
#include <bobgui/bobguilistitemfactory.h>
#include <bobgui/deprecated/bobguiliststore.h>
#include <bobgui/bobguilistview.h>
#include <bobgui/deprecated/bobguilockbutton.h>
#include <bobgui/bobguimain.h>
#include <bobgui/bobguimaplistmodel.h>
#include <bobgui/bobguimediacontrols.h>
#include <bobgui/bobguimediafile.h>
#include <bobgui/bobguimediastream.h>
#include <bobgui/bobguimenubutton.h>
#include <bobgui/deprecated/bobguimessagedialog.h>
#include <bobgui/bobguimountoperation.h>
#include <bobgui/bobguimultifilter.h>
#include <bobgui/bobguimultiselection.h>
#include <bobgui/bobguimultisorter.h>
#include <bobgui/bobguinative.h>
#include <bobgui/bobguinativedialog.h>
#include <bobgui/bobguinoselection.h>
#include <bobgui/bobguinotebook.h>
#include <bobgui/bobguinumericsorter.h>
#include <bobgui/bobguiorientable.h>
#include <bobgui/bobguioverlay.h>
#include <bobgui/bobguioverlaylayout.h>
#include <bobgui/bobguipadcontroller.h>
#include <bobgui/print/bobguipagesetup.h>
#include <bobgui/bobguipaned.h>
#include <bobgui/print/bobguipapersize.h>
#include <bobgui/bobguipasswordentry.h>
#include <bobgui/bobguipasswordentrybuffer.h>
#include <bobgui/bobguipicture.h>
#include <bobgui/bobguipopover.h>
#include <bobgui/bobguipopoverbin.h>
#include <bobgui/bobguipopovermenu.h>
#include <bobgui/bobguipopovermenubar.h>
#include <bobgui/bobguiprintdialog.h>
#include <bobgui/print/bobguiprintcontext.h>
#include <bobgui/print/bobguiprintoperation.h>
#include <bobgui/print/bobguiprintoperationpreview.h>
#include <bobgui/print/bobguiprintsettings.h>
#include <bobgui/bobguiprogressbar.h>
#include <bobgui/bobguirange.h>
#include <bobgui/bobguirecentmanager.h>
#include <bobgui/deprecated/bobguirender.h>
#include <bobgui/bobguirevealer.h>
#include <bobgui/bobguiroot.h>
#include <bobgui/bobguiscale.h>
#include <bobgui/bobguiscalebutton.h>
#include <bobgui/bobguiscrollable.h>
#include <bobgui/bobguiscrollbar.h>
#include <bobgui/bobguiscrollinfo.h>
#include <bobgui/bobguiscrolledwindow.h>
#include <bobgui/bobguisearchbar.h>
#include <bobgui/bobguisearchentry.h>
#include <bobgui/bobguisectionmodel.h>
#include <bobgui/bobguiselectionfiltermodel.h>
#include <bobgui/bobguiselectionmodel.h>
#include <bobgui/bobguiseparator.h>
#include <bobgui/bobguisettings.h>
#include <bobgui/bobguishortcut.h>
#include <bobgui/bobguishortcutaction.h>
#include <bobgui/bobguishortcutcontroller.h>
#include <bobgui/bobguishortcutmanager.h>
#include <bobgui/deprecated/bobguishortcutlabel.h>
#include <bobgui/deprecated/bobguishortcutsgroup.h>
#include <bobgui/deprecated/bobguishortcutssection.h>
#include <bobgui/deprecated/bobguishortcutsshortcut.h>
#include <bobgui/deprecated/bobguishortcutswindow.h>
#include <bobgui/bobguishortcuttrigger.h>
#include <bobgui/deprecated/bobguishow.h>
#include <bobgui/bobguisignallistitemfactory.h>
#include <bobgui/bobguisingleselection.h>
#include <bobgui/bobguislicelistmodel.h>
#include <bobgui/bobguisnapshot.h>
#include <bobgui/bobguisorter.h>
#include <bobgui/bobguisortlistmodel.h>
#include <bobgui/bobguistacksidebar.h>
#include <bobgui/bobguisizegroup.h>
#include <bobgui/bobguisizerequest.h>
#include <bobgui/bobguispinbutton.h>
#include <bobgui/bobguispinner.h>
#include <bobgui/bobguistack.h>
#include <bobgui/bobguistackswitcher.h>
#include <bobgui/deprecated/bobguistatusbar.h>
#include <bobgui/bobguistringfilter.h>
#include <bobgui/bobguistringlist.h>
#include <bobgui/bobguistringsorter.h>
#include <bobgui/deprecated/bobguistylecontext.h>
#include <bobgui/bobguistyleprovider.h>
#include <bobgui/bobguiswitch.h>
#include <bobgui/bobguisymbolicpaintable.h>
#include <bobgui/bobguitext.h>
#include <bobgui/bobguitextbuffer.h>
#include <bobgui/bobguitextchild.h>
#include <bobgui/bobguitextiter.h>
#include <bobgui/bobguitextmark.h>
#include <bobgui/bobguitexttag.h>
#include <bobgui/bobguitexttagtable.h>
#include <bobgui/bobguitextview.h>
#include <bobgui/bobguitogglebutton.h>
#include <bobgui/bobguitooltip.h>
#include <bobgui/bobguitestatcontext.h>
#include <bobgui/bobguitestutils.h>
#include <bobgui/deprecated/bobguitreednd.h>
#include <bobgui/bobguitreeexpander.h>
#include <bobgui/bobguitreelistmodel.h>
#include <bobgui/bobguitreelistrowsorter.h>
#include <bobgui/deprecated/bobguitreemodel.h>
#include <bobgui/deprecated/bobguitreemodelfilter.h>
#include <bobgui/deprecated/bobguitreemodelsort.h>
#include <bobgui/deprecated/bobguitreeselection.h>
#include <bobgui/deprecated/bobguitreesortable.h>
#include <bobgui/deprecated/bobguitreestore.h>
#include <bobgui/deprecated/bobguitreeview.h>
#include <bobgui/deprecated/bobguitreeviewcolumn.h>
#include <bobgui/bobguitypebuiltins.h>
#include <bobgui/bobguitypes.h>
#include <bobgui/bobguiurilauncher.h>
#include <bobgui/bobguiversion.h>
#include <bobgui/bobguivideo.h>
#include <bobgui/bobguiviewport.h>
#include <bobgui/deprecated/bobguivolumebutton.h>
#include <bobgui/bobguiwidget.h>
#include <bobgui/bobguiwidgetpaintable.h>
#include <bobgui/bobguiwindow.h>
#include <bobgui/bobguiwindowcontrols.h>
#include <bobgui/bobguiwindowgroup.h>
#include <bobgui/bobguiwindowhandle.h>

#undef __BOBGUI_H_INSIDE__

