/*
 * Copyright © 2012 Red Hat Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 *
 * Authors: Benjamin Otte <otte@gnome.org>
 */

#pragma once

#include <glib-object.h>

G_BEGIN_DECLS

static const int core_props[] = {
  BOBGUI_CSS_PROPERTY_COLOR,
  BOBGUI_CSS_PROPERTY_DPI,
  BOBGUI_CSS_PROPERTY_FONT_SIZE,
  BOBGUI_CSS_PROPERTY_ICON_PALETTE
};

static const int background_props[] = {
  BOBGUI_CSS_PROPERTY_BACKGROUND_COLOR,
  BOBGUI_CSS_PROPERTY_BOX_SHADOW,
  BOBGUI_CSS_PROPERTY_BACKGROUND_CLIP,
  BOBGUI_CSS_PROPERTY_BACKGROUND_ORIGIN,
  BOBGUI_CSS_PROPERTY_BACKGROUND_SIZE,
  BOBGUI_CSS_PROPERTY_BACKGROUND_POSITION,
  BOBGUI_CSS_PROPERTY_BACKGROUND_REPEAT,
  BOBGUI_CSS_PROPERTY_BACKGROUND_IMAGE,
  BOBGUI_CSS_PROPERTY_BACKGROUND_BLEND_MODE
};

static const int border_props[] = {
  BOBGUI_CSS_PROPERTY_BORDER_TOP_STYLE,
  BOBGUI_CSS_PROPERTY_BORDER_TOP_WIDTH,
  BOBGUI_CSS_PROPERTY_BORDER_LEFT_STYLE,
  BOBGUI_CSS_PROPERTY_BORDER_LEFT_WIDTH,
  BOBGUI_CSS_PROPERTY_BORDER_BOTTOM_STYLE,
  BOBGUI_CSS_PROPERTY_BORDER_BOTTOM_WIDTH,
  BOBGUI_CSS_PROPERTY_BORDER_RIGHT_STYLE,
  BOBGUI_CSS_PROPERTY_BORDER_RIGHT_WIDTH,
  BOBGUI_CSS_PROPERTY_BORDER_TOP_LEFT_RADIUS,
  BOBGUI_CSS_PROPERTY_BORDER_TOP_RIGHT_RADIUS,
  BOBGUI_CSS_PROPERTY_BORDER_BOTTOM_RIGHT_RADIUS,
  BOBGUI_CSS_PROPERTY_BORDER_BOTTOM_LEFT_RADIUS,
  BOBGUI_CSS_PROPERTY_BORDER_TOP_COLOR,
  BOBGUI_CSS_PROPERTY_BORDER_RIGHT_COLOR,
  BOBGUI_CSS_PROPERTY_BORDER_BOTTOM_COLOR,
  BOBGUI_CSS_PROPERTY_BORDER_LEFT_COLOR,
  BOBGUI_CSS_PROPERTY_BORDER_IMAGE_SOURCE,
  BOBGUI_CSS_PROPERTY_BORDER_IMAGE_REPEAT,
  BOBGUI_CSS_PROPERTY_BORDER_IMAGE_SLICE,
  BOBGUI_CSS_PROPERTY_BORDER_IMAGE_WIDTH
};

static const int icon_props[] = {
  BOBGUI_CSS_PROPERTY_ICON_SIZE,
  BOBGUI_CSS_PROPERTY_ICON_SHADOW,
  BOBGUI_CSS_PROPERTY_ICON_STYLE,
  BOBGUI_CSS_PROPERTY_ICON_WEIGHT,
};

static const int outline_props[] = {
  BOBGUI_CSS_PROPERTY_OUTLINE_STYLE,
  BOBGUI_CSS_PROPERTY_OUTLINE_WIDTH,
  BOBGUI_CSS_PROPERTY_OUTLINE_OFFSET,
  BOBGUI_CSS_PROPERTY_OUTLINE_COLOR,
};

static const int font_props[] = {
  BOBGUI_CSS_PROPERTY_FONT_FAMILY,
  BOBGUI_CSS_PROPERTY_FONT_STYLE,
  BOBGUI_CSS_PROPERTY_FONT_WEIGHT,
  BOBGUI_CSS_PROPERTY_FONT_STRETCH,
  BOBGUI_CSS_PROPERTY_LETTER_SPACING,
  BOBGUI_CSS_PROPERTY_TEXT_SHADOW,
  BOBGUI_CSS_PROPERTY_CARET_COLOR,
  BOBGUI_CSS_PROPERTY_SECONDARY_CARET_COLOR,
  BOBGUI_CSS_PROPERTY_FONT_FEATURE_SETTINGS,
  BOBGUI_CSS_PROPERTY_FONT_VARIATION_SETTINGS,
  BOBGUI_CSS_PROPERTY_LINE_HEIGHT,
};

static const int text_decoration_props[] = {
  BOBGUI_CSS_PROPERTY_TEXT_DECORATION_LINE,
  BOBGUI_CSS_PROPERTY_TEXT_DECORATION_COLOR,
  BOBGUI_CSS_PROPERTY_TEXT_DECORATION_STYLE,
};

static const int font_variant_props[] = {
  BOBGUI_CSS_PROPERTY_TEXT_TRANSFORM,
  BOBGUI_CSS_PROPERTY_FONT_KERNING,
  BOBGUI_CSS_PROPERTY_FONT_VARIANT_LIGATURES,
  BOBGUI_CSS_PROPERTY_FONT_VARIANT_POSITION,
  BOBGUI_CSS_PROPERTY_FONT_VARIANT_CAPS,
  BOBGUI_CSS_PROPERTY_FONT_VARIANT_NUMERIC,
  BOBGUI_CSS_PROPERTY_FONT_VARIANT_ALTERNATES,
  BOBGUI_CSS_PROPERTY_FONT_VARIANT_EAST_ASIAN,
};

static const int animation_props[] = {
  BOBGUI_CSS_PROPERTY_ANIMATION_NAME,
  BOBGUI_CSS_PROPERTY_ANIMATION_DURATION,
  BOBGUI_CSS_PROPERTY_ANIMATION_TIMING_FUNCTION,
  BOBGUI_CSS_PROPERTY_ANIMATION_ITERATION_COUNT,
  BOBGUI_CSS_PROPERTY_ANIMATION_DIRECTION,
  BOBGUI_CSS_PROPERTY_ANIMATION_PLAY_STATE,
  BOBGUI_CSS_PROPERTY_ANIMATION_DELAY,
  BOBGUI_CSS_PROPERTY_ANIMATION_FILL_MODE,
};

static const int transition_props[] = {
  BOBGUI_CSS_PROPERTY_TRANSITION_PROPERTY,
  BOBGUI_CSS_PROPERTY_TRANSITION_DURATION,
  BOBGUI_CSS_PROPERTY_TRANSITION_TIMING_FUNCTION,
  BOBGUI_CSS_PROPERTY_TRANSITION_DELAY,
};

static const int size_props[] = {
  BOBGUI_CSS_PROPERTY_MARGIN_TOP,
  BOBGUI_CSS_PROPERTY_MARGIN_LEFT,
  BOBGUI_CSS_PROPERTY_MARGIN_BOTTOM,
  BOBGUI_CSS_PROPERTY_MARGIN_RIGHT,
  BOBGUI_CSS_PROPERTY_PADDING_TOP,
  BOBGUI_CSS_PROPERTY_PADDING_LEFT,
  BOBGUI_CSS_PROPERTY_PADDING_BOTTOM,
  BOBGUI_CSS_PROPERTY_PADDING_RIGHT,
  BOBGUI_CSS_PROPERTY_BORDER_SPACING,
  BOBGUI_CSS_PROPERTY_MIN_WIDTH,
  BOBGUI_CSS_PROPERTY_MIN_HEIGHT,
};

static const int other_props[] = {
  BOBGUI_CSS_PROPERTY_ICON_SOURCE,
  BOBGUI_CSS_PROPERTY_ICON_TRANSFORM,
  BOBGUI_CSS_PROPERTY_ICON_FILTER,
  BOBGUI_CSS_PROPERTY_TRANSFORM,
  BOBGUI_CSS_PROPERTY_TRANSFORM_ORIGIN,
  BOBGUI_CSS_PROPERTY_OPACITY,
  BOBGUI_CSS_PROPERTY_BACKDROP_FILTER,
  BOBGUI_CSS_PROPERTY_FILTER,
};

static const int used_props[] = {
  BOBGUI_CSS_PROPERTY_COLOR,
  BOBGUI_CSS_PROPERTY_ICON_PALETTE,
  BOBGUI_CSS_PROPERTY_BACKGROUND_COLOR,
  BOBGUI_CSS_PROPERTY_BOX_SHADOW,
  BOBGUI_CSS_PROPERTY_BACKGROUND_IMAGE,
  BOBGUI_CSS_PROPERTY_BORDER_TOP_COLOR,
  BOBGUI_CSS_PROPERTY_BORDER_RIGHT_COLOR,
  BOBGUI_CSS_PROPERTY_BORDER_BOTTOM_COLOR,
  BOBGUI_CSS_PROPERTY_BORDER_LEFT_COLOR,
  BOBGUI_CSS_PROPERTY_BORDER_IMAGE_SOURCE,
  BOBGUI_CSS_PROPERTY_ICON_SHADOW,
  BOBGUI_CSS_PROPERTY_OUTLINE_COLOR,
  BOBGUI_CSS_PROPERTY_CARET_COLOR,
  BOBGUI_CSS_PROPERTY_SECONDARY_CARET_COLOR,
  BOBGUI_CSS_PROPERTY_TEXT_SHADOW,
  BOBGUI_CSS_PROPERTY_TEXT_DECORATION_COLOR,
  BOBGUI_CSS_PROPERTY_ICON_SOURCE,
};

/* Maps back from css property ids to position in used_props.
 * -1 means 'not present'.
 */
static const int used_props_map[] = {
  0, /* color */
  -1, -1,
  1, /* icon-palette */
  2, /* background-color */
  -1, -1, -1, -1, -1, -1,
  15, /* text-decoration-color */
  -1, -1, -1, -1, -1, -1, -1, -1,
  -1,
  14, /* text-shadow */
  3, /* box-shadow */
  -1, -1, -1, -1, -1, -1, -1, -1,
  -1, -1, -1, -1, -1, -1, -1, -1,
  -1, -1, -1, -1, -1, -1, -1, -1,
  -1, -1, -1,
  5, /* border-top-color */
  6, /* border-right-color */
  7, /* border-bottom-color */
  8, /* border-left-color */
  11, /* outline-color */
  -1,
  4, /* background-image */
  -1,
  9, /* border-image-source */
  -1, -1, -1,
  16, /* icon-source */
  -1,
  10, /* icon-shadow */
  -1, -1, -1, -1, -1, -1, -1, -1,
  -1, -1, -1, -1, -1, -1, -1, -1,
  -1, -1, -1, -1, -1, -1, -1, -1,
  12, /* caret-color */
  13, /* secondary-caret-color */
  -1, -1, -1, 
};

G_STATIC_ASSERT (G_N_ELEMENTS (used_props_map) == BOBGUI_CSS_PROPERTY_N_PROPERTIES);

G_END_DECLS
